server:
  port: 8080

spring:
  application:
    name: drmp-platform
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/drmp?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai}
    username: ${SPRING_DATASOURCE_USERNAME:drmp}
    password: ${SPRING_DATASOURCE_PASSWORD:drmp123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: DrmpHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        use_sql_comments: false
        jdbc:
          batch_size: 20
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
    open-in-view: false
  
  redis:
    host: ${SPRING_REDIS_HOST:redis}
    port: 6379
    password: ${SPRING_REDIS_PASSWORD:redis123456}
    database: 0
    timeout: 6000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: flyway_schema_history
    baseline-version: 0
  
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

# JWT Configuration
jwt:
  secret: drmp2024SecretKeyForJWTTokenGenerationAndValidationInDockerEnvironment
  expiration: 7200000 # 2 hours
  refresh-expiration: 604800000 # 7 days
  header: Authorization
  prefix: Bearer

# Application Configuration
app:
  cors:
    allowed-origins: http://localhost,http://localhost:3000,http://localhost:80
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    exposed-headers: Authorization
    allow-credentials: true
    max-age: 3600
  
  file:
    upload-dir: /app/uploads
    max-size: 104857600 # 100MB
    allowed-extensions: jpg,jpeg,png,pdf,doc,docx,xls,xlsx
  
  security:
    password-strength: medium
    max-login-attempts: 5
    lock-time-minutes: 30

# Logging Configuration
logging:
  level:
    root: INFO
    com.drmp: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /app/logs/drmp.log
    max-size: 10MB
    max-history: 30

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized