server:
  port: 8080

spring:
  application:
    name: drmp-backend

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:drmp}?ssl=false
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  # Disable Flyway - tables already exist
  flyway:
    enabled: false

  # Disable Redis completely
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

  # Disable cache (which might use Redis)
  cache:
    type: none

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

jwt:
  secret: drmp-secret-key-2024
  expiration: 7200000  # 2 hours in milliseconds
  refresh-expiration: 604800000  # 7 days in milliseconds

logging:
  level:
    root: INFO
    com.drmp: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

# File upload configuration
file:
  upload-dir: /tmp/drmp/uploads/

# Disable security for development
management:
  endpoints:
    web:
      exposure:
        include: "*"