server:
  port: 8080

spring:
  application:
    name: drmp-backend

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/drmp?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: drmp123456
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  # Disable Redis completely
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

  # Disable cache (which might use Redis)
  cache:
    type: none

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

jwt:
  secret: drmp-secret-key-2024
  expiration: 7200000  # 2 hours in milliseconds
  refresh-expiration: 604800000  # 7 days in milliseconds

logging:
  level:
    root: INFO
    com.drmp: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

# File upload configuration
file:
  upload-dir: /tmp/drmp/uploads/

# Disable security for development
management:
  endpoints:
    web:
      exposure:
        include: "*"