# 开发环境配置
spring:
  jpa:
    hibernate:
      ddl-auto: update  # 开发环境可以自动更新schema
    show-sql: true

  flyway:
    clean-disabled: false  # 开发环境允许clean操作

# 开发环境日志配置
logging:
  level:
    root: INFO
    com.drmp: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/drmp-dev.log
    max-size: 10MB
    max-history: 7
