server:
  port: 8080
  servlet:
    context-path: /api
  compression:
    enabled: true

spring:
  application:
    name: drmp-platform
  
  profiles:
    active: dev
  
  main:
    allow-bean-definition-overriding: true
  
  datasource:
    url: jdbc:h2:mem:drmp;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: DrmpHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        use_sql_comments: true
        jdbc:
          batch_size: 20
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
    open-in-view: false
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # 禁用Redis，使用内存缓存
  cache:
    type: caffeine
  
  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: flyway_schema_history
    baseline-version: 0
  
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

# JWT Configuration
jwt:
  secret: drmp2024SecretKeyForJWTTokenGenerationAndValidation
  expiration: 7200000 # 2 hours in milliseconds
  refresh-expiration: 604800000 # 7 days in milliseconds
  header: Authorization
  prefix: Bearer

# Application Configuration
app:
  cors:
    allowed-origins: http://localhost:3000,http://localhost:3001
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    exposed-headers: Authorization
    allow-credentials: true
    max-age: 3600
  
  file:
    upload-dir: ./uploads
    max-size: 104857600 # 100MB in bytes
    allowed-extensions: jpg,jpeg,png,pdf,doc,docx,xls,xlsx
  
  security:
    password-strength: medium
    max-login-attempts: 5
    lock-time-minutes: 30

# Logging Configuration
logging:
  level:
    root: INFO
    com.drmp: DEBUG
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/drmp.log
    max-size: 10MB
    max-history: 30

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Springdoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /v1/**